---
title: Hardik Goswami
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: geniushkg@gmail.com
author: Hardik Goswami
description: Software Engineering blog , codes , gist and tutorials with explanation
  generally on android / python ML
baseurl: ''
url: http://hardikgoswami.com
date_format: "%b %-d, %Y"
google_verification: 
google_analytics: UA-82328245-1
google_tag_manager: 
bing_verification: 
animated: false
show_related_posts: false
show_post_footers: false
show_social_icons: false
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
disqus_shortname: 
facebook_comments: 
facebook_appid: 
facebook_comments_number: 10
github_username: geniushkg
bitbucket_username: 
stackoverflow_id: 
twitter_username: 
skype_username: goswami.hardik.k
steam_nickname: 
google_plus_id: 
linkedin_username: geniushkg
angellist_username: 
medium_id: 
bitcoin_url: 
paypal_url: 
flattr_button: 
show_sharing_icons: false
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
text:
  pagination:
    newer: Newer
    older: Older
  share_buttons:
    text: Share this post!
    facebook: Share on Facebook
    twitter: Share on Twitter
    googleplus: Share on Google+
    linkedin: Share on LinkedIn
    digg: Share on Digg
    tumblr: Share on Tumblr
    reddit: Share on Reddit
    stumbleupon: Share on StumbleUpon
    hackernews: Share on Hacker News
  post:
    updated: Updated
    minute_read: minute read
    related_posts: Related Posts
  index:
    coming_soon: Coming soon...
  contact:
    email: Email Address
    content: What would you like to say?
    subject: New submission!
    submit: Say Hello
    ajax:
      sending: sending..
      sent: Message sent!
      error: Error!
  thanks: Thanks for contacting us. We will reply as soon as possible.
  og_locale: en_US
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: pretty
paginate: 4
sass:
  compressed: true
gems:
- jekyll-paginate
- jekyll-sitemap
exclude:
- vendor
